// 班級結局系統：20 正向 + 10 待努力
// 依「一學年結束時的最終 state」判定。selectEnding 由上而下取第一個符合者，
// 因此陣列順序＝優先序（稀有/亮眼者在前，最後各放一個保底）。
import { literacyRank } from './state.js';

// 從 state 推導好判讀的數值
export function deriveOutcome(state) {
  const st = state.stats;
  const statVals = [st.cohesion, st.climate, st.trust, st.honor, st.roleModel];
  const oct = Object.values(state.octalysis || {}).reduce((a, b) => a + b, 0);
  return {
    lit: state.literacy || 0,
    rank: literacyRank(state.literacy || 0),
    cohesion: st.cohesion, climate: st.climate, trust: st.trust,
    honor: st.honor, roleModel: st.roleModel,
    hp: state.resources.hp, budget: state.resources.budget,
    badges: state.badges.length,
    acc: state.answered ? Math.round((state.correct / state.answered) * 100) : 0,
    minStat: Math.min(...statVals),
    avgStat: Math.round(statVals.reduce((a, b) => a + b, 0) / statVals.length),
    oct,
    hard: !!state.hard,
    pressure: state.pressure || 0,
  };
}

// kind: 'good' 正向｜'effort' 待努力
// mechanism：對外說明「怎麼達成」（放在結局網頁）
// cond(o)：用 deriveOutcome 結果判定
export const ENDINGS = [
  // ───────── 困難版專屬（校事會議地獄模式；只在 hard 時觸發，置頂優先判定）─────────
  { id: 'hd_clear', kind: 'good', title: '清白歸來', img: 'assets/endings/e04.png',
    desc: '一整年的家長投訴與校事會議反覆訪談，你都據實以對、依法以行。調查還你清白，你昂首走完這一年——沒有人能否定你帶過這一班。',
    mechanism: '困難版：撐完 40 週，結業時投訴壓力 ≤ 40 且 五項指標平均 ≥ 55（守住清白也守住班級）。',
    cond: (o) => o.hard && o.pressure <= 40 && o.avgStat >= 55 },
  { id: 'hd_resign', kind: 'effort', title: '黯然請辭', img: 'assets/endings/e29.png',
    desc: '投訴沒有停過，調查一場接一場，學年末你終究遞出了辭呈。這不是你不夠好——是這套制度太重。願你休息夠了，還願意再回到孩子身邊。',
    mechanism: '困難版：結業時投訴壓力 ≥ 85（壓力長期失控，瀕臨停聘）。',
    cond: (o) => o.hard && o.pressure >= 85 },

  // ───────── 20 正向 ─────────
  { id: 'e01', kind: 'good', title: '法規典範導師', img: 'assets/endings/e01.png',
    desc: '你把每一條教師法、通報與管教規範都內化成直覺，成為全校信賴的法規後盾。',
    mechanism: '最終法規素養達 1900 分（幾乎每題都答到最佳解的典範級表現）。',
    cond: (o) => o.lit >= 1900 },
  { id: 'e02', kind: 'good', title: '全能金牌導師', img: 'assets/endings/e02.png',
    desc: '凝聚、班風、信任、榮譽、典範樣樣到位，這一班成了全校的模範。',
    mechanism: '五項班級指標（凝聚／班風／信任／榮譽／典範）全部 ≥ 78。',
    cond: (o) => o.minStat >= 78 },
  { id: 'e03', kind: 'good', title: '全班一條心', img: 'assets/endings/e03.png',
    desc: '畢業這天，孩子們手勾著手不肯散場——你帶出了真正的凝聚力。',
    mechanism: '凝聚 ≥ 85 且 班風 ≥ 85。',
    cond: (o) => o.cohesion >= 85 && o.climate >= 85 },
  { id: 'e04', kind: 'good', title: '永遠的依靠', img: 'assets/endings/e04.png',
    desc: '畢業多年後，學生遇到難關第一個想到的還是你。',
    mechanism: '信任 ≥ 90。',
    cond: (o) => o.trust >= 90 },
  { id: 'e05', kind: 'good', title: '身教典範', img: 'assets/endings/e05.png',
    desc: '你沒有說太多大道理，孩子卻把你的樣子，活成了自己的樣子。',
    mechanism: '典範 ≥ 90。',
    cond: (o) => o.roleModel >= 90 },
  { id: 'e06', kind: 'good', title: '榮譽之班', img: 'assets/endings/e06.png',
    desc: '榮譽榜上滿滿都是這一班的名字，孩子們抬頭挺胸地畢業。',
    mechanism: '榮譽 ≥ 88。',
    cond: (o) => o.honor >= 88 },
  { id: 'e07', kind: 'good', title: '春風化雨', img: 'assets/endings/e07.png',
    desc: '溫柔而堅定，你讓每個孩子都被好好接住。',
    mechanism: '典範 ≥ 85 且 凝聚 ≥ 80。',
    cond: (o) => o.roleModel >= 85 && o.cohesion >= 80 },
  { id: 'e08', kind: 'good', title: '親師同盟', img: 'assets/endings/e08.png',
    desc: '家長成了你最強的後盾，親師之間沒有對立，只有合作。',
    mechanism: '信任 ≥ 85 且 榮譽 ≥ 75。',
    cond: (o) => o.trust >= 85 && o.honor >= 75 },
  { id: 'e09', kind: 'good', title: '法理兼顧的智者', img: 'assets/endings/e09.png',
    desc: '懂法、也懂孩子；你在規範與溫度之間找到了最好的平衡。',
    mechanism: '法規素養 ≥ 1200 且 信任 ≥ 78。',
    cond: (o) => o.lit >= 1200 && o.trust >= 78 },
  { id: 'e10', kind: 'good', title: '危機處理達人', img: 'assets/endings/e10.png',
    desc: '再棘手的突發狀況，你都能依法、依理、依情穩穩接住。',
    mechanism: '法規素養 ≥ 1100 且 法規答對率 ≥ 85%。',
    cond: (o) => o.lit >= 1100 && o.acc >= 85 },
  { id: 'e11', kind: 'good', title: '滿級勳章蒐集者', img: 'assets/endings/e11.png',
    desc: '一路上的隱藏挑戰你幾乎全收，獎勵牆閃閃發亮。',
    mechanism: '取得 3 個（含）以上勳章。',
    cond: (o) => o.badges >= 3 },
  { id: 'e12', kind: 'good', title: '高昂鬥志班', img: 'assets/endings/e12.png',
    desc: '這一班總是最有活力，運動會、競賽都拿出拚勁。',
    mechanism: '凝聚 ≥ 80 且 榮譽 ≥ 80。',
    cond: (o) => o.cohesion >= 80 && o.honor >= 80 },
  { id: 'e13', kind: 'good', title: '祥和好班風', img: 'assets/endings/e13.png',
    desc: '教室裡總是和和氣氣，孩子在這裡很安心。',
    mechanism: '班風 ≥ 85 且 心力 ≥ 55（你也照顧好自己）。',
    cond: (o) => o.climate >= 85 && o.hp >= 55 },
  { id: 'e14', kind: 'good', title: '精打細算的管家', img: 'assets/endings/e14.png',
    desc: '班費管得清清楚楚，活動辦得有聲有色，分文不浪費。',
    mechanism: '班費結餘 ≥ 5000 且 凝聚 ≥ 70。',
    cond: (o) => o.budget >= 5000 && o.cohesion >= 70 },
  { id: 'e15', kind: 'good', title: '鐵血高效導師', img: 'assets/endings/e15.png',
    desc: '判斷精準、決策俐落，幾乎每一題都正中要害。',
    mechanism: '法規答對率 ≥ 90%。',
    cond: (o) => o.acc >= 90 },
  { id: 'e16', kind: 'good', title: '永不放棄', img: 'assets/endings/e16.png',
    desc: '即使再累，你也撐到了最後，並守住了專業底線。',
    mechanism: '結業時心力 ≥ 55 且 法規素養 ≥ 800。',
    cond: (o) => o.hp >= 55 && o.lit >= 800 },
  { id: 'e17', kind: 'good', title: '暖心守護者', img: 'assets/endings/e17.png',
    desc: '你讓每個孩子都覺得「老師永遠站在我這邊」。',
    mechanism: '信任 ≥ 80 且 典範 ≥ 80。',
    cond: (o) => o.trust >= 80 && o.roleModel >= 80 },
  { id: 'e18', kind: 'good', title: '八角全開大師', img: 'assets/endings/e18.png',
    desc: '使命、成就、關聯、未知……你把班級經營玩成了一門藝術。',
    mechanism: '八大核心驅動力總充能 ≥ 40，且五項指標平均 ≥ 68（多元且高水準經營）。',
    cond: (o) => o.oct >= 40 && o.avgStat >= 68 },
  { id: 'e19', kind: 'good', title: '模範班級', img: 'assets/endings/e19.png',
    desc: '凝聚、班風、榮譽三線並進，這一班被全校當成標竿。',
    mechanism: '凝聚／班風／榮譽 三項皆 ≥ 80。',
    cond: (o) => o.cohesion >= 80 && o.climate >= 80 && o.honor >= 80 },
  { id: 'e20', kind: 'good', title: '圓滿畢業', img: 'assets/endings/e20.png',
    desc: '沒有驚天動地，但你穩穩地把這一班帶到了畢業，孩子們笑著向你揮手。',
    mechanism: '正向結局保底：法規素養 ≥ 350（合格以上）且 五項指標平均 ≥ 55。',
    cond: (o) => o.lit >= 350 && o.avgStat >= 55 },

  // ───────── 10 待努力 ─────────
  { id: 'e21', kind: 'effort', title: '心力透支', img: 'assets/endings/e21.png',
    desc: '你把自己燃燒到只剩灰燼——記得，照顧好自己才能走得久。',
    mechanism: '結業時心力 ≤ 15。',
    cond: (o) => o.hp <= 15 },
  { id: 'e22', kind: 'effort', title: '信任崩盤', img: 'assets/endings/e22.png',
    desc: '幾次處理失了分寸，孩子和家長都把心收了回去。',
    mechanism: '信任 ≤ 30。',
    cond: (o) => o.trust <= 30 },
  { id: 'e23', kind: 'effort', title: '班級渙散', img: 'assets/endings/e23.png',
    desc: '少了凝聚的軸心，這一班各走各的，始終湊不到一塊。',
    mechanism: '凝聚 ≤ 35。',
    cond: (o) => o.cohesion <= 35 },
  { id: 'e24', kind: 'effort', title: '班風低迷', img: 'assets/endings/e24.png',
    desc: '教室裡氣氛總是悶悶的，孩子提不起勁。',
    mechanism: '班風 ≤ 35。',
    cond: (o) => o.climate <= 35 },
  { id: 'e25', kind: 'effort', title: '紙上談兵', img: 'assets/endings/e25.png',
    desc: '臨場一次次抓不到關鍵，法規還要再下功夫。',
    mechanism: '法規答對率 < 50%。',
    cond: (o) => o.acc < 50 },
  { id: 'e26', kind: 'effort', title: '法規生疏', img: 'assets/endings/e26.png',
    desc: '太多該守的線沒守住，下一年得把法規重新讀熟。',
    mechanism: '法規素養 < 350（仍是新手導師）。',
    cond: (o) => o.lit < 350 },
  { id: 'e27', kind: 'effort', title: '入不敷出', img: 'assets/endings/e27.png',
    desc: '班費透支，活動辦得綁手綁腳，財務得重新規劃。',
    mechanism: '班費結餘為負數。',
    cond: (o) => o.budget < 0 },
  { id: 'e28', kind: 'effort', title: '顧此失彼', img: 'assets/endings/e28.png',
    desc: '某一面顧得很好，卻有一塊嚴重失衡，整體被拖了下來。',
    mechanism: '任一班級指標 ≤ 30（出現明顯短板）。',
    cond: (o) => o.minStat <= 30 },
  { id: 'e29', kind: 'effort', title: '孤軍奮戰', img: 'assets/endings/e29.png',
    desc: '你很努力，但缺了信任與身教的連結，總覺得一個人在撐。',
    mechanism: '信任 < 45 且 典範 < 45。',
    cond: (o) => o.trust < 45 && o.roleModel < 45 },
  { id: 'e30', kind: 'effort', title: '跌跌撞撞的一年', img: 'assets/endings/e30.png',
    desc: '這一年走得磕磕絆絆，但每個踉蹌都是明年的養分。再來一次吧！',
    mechanism: '待努力保底：未達任何正向結局門檻時的結局。',
    cond: () => true },
];

export function selectEnding(state) {
  const o = deriveOutcome(state);
  return ENDINGS.find((e) => e.cond(o)) || ENDINGS[ENDINGS.length - 1];
}
